spring:
  application:
    name: restApiWithSpring
  datasource:
    url: jdbc:mysql://localhost:3306/rest_api_spring_gustainmars?useTimezone=true&serverTimezone=UTC
    username: gpmarques
    password: Mugiwara1!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
      show-sql: false
    open-in-view: false
logging:
  level:
    #root: WARN
    br.com.gustainMars: DEBUG